[package]
name = "tina-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tina-worker = { version = "0.1.0", path = "../tina-worker" }
tokio.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
qr2term = "0.3.3"
